website_site:
    resource: '../../src/Controller/'
    type:     annotation
    prefix:
        fr: '/fr'
        ar: '/ar'
#    host: '%domain_name_short%'

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
